<?php
//$Id$
/**
*
* Adds modifications to various site forms.
*
*/
function formmod_form_alter(&$form, $form_state, $form_id) {
// This part changes the user login form
if ($form_id == 'user_login') {
// Change the text below the username field to 'Enter your
username.'
$form['name']['#description'] = t('Enter your username.');
// Change the text on the submit button to 'enter'
$form['submit']['#value'] = t('let me in!');
}
// This part changes the user registration form
if ($form_id == 'user_register') {
// Change the text on the submit button to 'submit registration'
$form['submit']['#value'] = t('submit registration');
}
// This part changes the request password form
if ($form_id == 'user_pass') {
// Changes the data label to add basic instructions to form
$form['name']['#title'] =
t('Enter your username or email address, then click the request
password button');
// Change the text on the submit button to 'request password'
$form['submit']['#value'] = t('request password');
}
}